import { useNavigate } from 'react-router-dom'

export default function Disclaimer() {
  const navigate = useNavigate()

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--text)', fontFamily: 'inherit' }}>
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '48px 28px 80px' }}>
        <button
          onClick={() => navigate(-1)}
          style={{ background: 'none', border: 'none', color: 'var(--text-2)', cursor: 'pointer', fontSize: 13, fontFamily: 'inherit', marginBottom: 32, padding: 0, display: 'flex', alignItems: 'center', gap: 6 }}
        >
          ← Back
        </button>

        <div style={{ marginBottom: 40 }}>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.16em', textTransform: 'uppercase', color: 'var(--accent)', marginBottom: 10 }}>Legal</div>
          <h1 style={{ fontSize: 32, fontWeight: 800, margin: 0, marginBottom: 10 }}>Disclaimer</h1>
          <p style={{ color: 'var(--text-2)', fontSize: 14, margin: 0 }}>Last updated: May 13, 2026</p>
        </div>

        {/* Key disclaimer callout */}
        <div style={{
          background: 'rgba(245,158,11,0.08)',
          border: '1px solid rgba(245,158,11,0.3)',
          borderLeft: '4px solid var(--warning)',
          borderRadius: '0 10px 10px 0',
          padding: '18px 22px',
          marginBottom: 36,
        }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--warning)', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.08em' }}>Important Notice</div>
          <div style={{ fontSize: 14, lineHeight: 1.7, color: 'var(--text)' }}>
            RIA Intelligence is a productivity platform for financial professionals. It does <strong>not</strong> provide investment advice. All AI-generated content must be independently verified before use in client communications or investment decisions.
          </div>
        </div>

        <div style={{ fontSize: 14.5, lineHeight: 1.85, color: 'var(--text-2)' }}>

          <Section title="Not Investment Advice">
            RIA Intelligence is not a registered investment advisor, broker-dealer, or financial planner. Nothing provided through this platform — including morning briefings, SEC filing summaries, market data summaries, client email drafts, or any other content — constitutes investment advice, a recommendation to buy or sell any security, or financial planning advice of any kind.
            <br /><br />
            The platform is designed as a productivity and research tool to help registered investment advisors work more efficiently. All investment decisions remain solely your responsibility and the responsibility of your clients.
          </Section>

          <Section title="AI-Generated Content">
            Morning briefings, SEC filing summaries, and client email drafts are generated using artificial intelligence (Anthropic's Claude). While we aim for accuracy, AI-generated content:
            <ul style={{ margin: '8px 0', paddingLeft: 20 }}>
              <li style={{ marginBottom: 8 }}>May contain factual errors, omissions, or mischaracterizations</li>
              <li style={{ marginBottom: 8 }}>May reflect the AI model's training data limitations or biases</li>
              <li style={{ marginBottom: 8 }}>Should never be shared with clients without your independent review and verification</li>
              <li style={{ marginBottom: 8 }}>Is not a substitute for your professional judgment, analysis, or fiduciary responsibility</li>
            </ul>
            You are solely responsible for reviewing and verifying any AI-generated content before using it in your practice. You assume all responsibility for how you use this content with clients.
          </Section>

          <Section title="Market Data">
            Market prices and related data are sourced from third-party providers (including Polygon.io) and may be:
            <ul style={{ margin: '8px 0', paddingLeft: 20 }}>
              <li style={{ marginBottom: 8 }}>Delayed by 15 minutes or more</li>
              <li style={{ marginBottom: 8 }}>Inaccurate or incomplete</li>
              <li style={{ marginBottom: 8 }}>Subject to errors from data providers</li>
            </ul>
            Do not rely on data from this platform for trade execution. Always verify prices with your broker or exchange data before making any trade.
          </Section>

          <Section title="SEC Filing Information">
            SEC filing summaries are generated by AI analyzing publicly available documents from SEC EDGAR. These summaries:
            <ul style={{ margin: '8px 0', paddingLeft: 20 }}>
              <li style={{ marginBottom: 8 }}>Are not reviewed by legal or compliance professionals</li>
              <li style={{ marginBottom: 8 }}>May omit material information from filings</li>
              <li style={{ marginBottom: 8 }}>Should not replace reading the actual filings for compliance or advisory purposes</li>
            </ul>
            Always refer to the original SEC filing on EDGAR for definitive information.
          </Section>

          <Section title="Past Performance">
            Any references to past market performance, historical returns, or historical events in briefing content are for informational context only and do not imply or guarantee future results.
          </Section>

          <Section title="Regulatory Compliance">
            You are responsible for ensuring that your use of this platform — including any client communications drafted or assisted by this platform — complies with all applicable regulations, including but not limited to SEC and FINRA rules, your firm's compliance policies, and applicable state regulations governing investment advisors.
            <br /><br />
            RIA Intelligence makes no representation that the use of AI-generated client communications complies with your specific regulatory obligations. Consult your compliance officer before using AI-drafted content in client communications.
          </Section>

          <Section title="No Guarantees">
            We do not guarantee the availability, accuracy, or completeness of the Service. The platform may experience downtime, and briefings may not be delivered on days when our systems or third-party data sources are unavailable.
          </Section>

          <Section title="Related Policies">
            <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
              <button onClick={() => navigate('/privacy')} style={{ background: 'none', border: 'none', color: 'var(--accent)', cursor: 'pointer', padding: 0, fontFamily: 'inherit', fontSize: 14.5, textDecoration: 'underline' }}>
                Privacy Policy
              </button>
              <button onClick={() => navigate('/terms')} style={{ background: 'none', border: 'none', color: 'var(--accent)', cursor: 'pointer', padding: 0, fontFamily: 'inherit', fontSize: 14.5, textDecoration: 'underline' }}>
                Terms of Service
              </button>
            </div>
          </Section>

        </div>
      </div>
    </div>
  )
}

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 32 }}>
      <h2 style={{ fontSize: 15, fontWeight: 700, color: 'var(--text)', marginBottom: 10, marginTop: 0 }}>{title}</h2>
      <div>{children}</div>
    </div>
  )
}
