import { useNavigate } from 'react-router-dom'

export default function TermsOfService() {
  const navigate = useNavigate()

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--text)', fontFamily: 'inherit' }}>
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '48px 28px 80px' }}>
        <button
          onClick={() => navigate(-1)}
          style={{ background: 'none', border: 'none', color: 'var(--text-2)', cursor: 'pointer', fontSize: 13, fontFamily: 'inherit', marginBottom: 32, padding: 0, display: 'flex', alignItems: 'center', gap: 6 }}
        >
          ← Back
        </button>

        <div style={{ marginBottom: 40 }}>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.16em', textTransform: 'uppercase', color: 'var(--accent)', marginBottom: 10 }}>Legal</div>
          <h1 style={{ fontSize: 32, fontWeight: 800, margin: 0, marginBottom: 10 }}>Terms of Service</h1>
          <p style={{ color: 'var(--text-2)', fontSize: 14, margin: 0 }}>Last updated: May 13, 2026</p>
        </div>

        <div style={{ fontSize: 14.5, lineHeight: 1.85, color: 'var(--text-2)' }}>

          <Section title="1. Acceptance of Terms">
            By accessing or using the VeloQuant platform (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service. These Terms form a binding agreement between you and VeloQuant ("we," "us," or "our").
          </Section>

          <Section title="2. Eligibility">
            You must be at least 18 years old and a licensed financial professional (or employee thereof) to use this Service. By using the Service, you represent and warrant that you meet these eligibility requirements. The Service is intended for use by registered investment advisors, financial planners, and related professionals in the United States.
          </Section>

          <Section title="3. Description of Service">
            VeloQuant provides:
            <ul style={{ margin: '8px 0', paddingLeft: 20 }}>
              <li style={{ marginBottom: 8 }}>AI-generated morning briefings summarizing market data, SEC filings, and news relevant to your tracked holdings</li>
              <li style={{ marginBottom: 8 }}>SEC filing alerts for companies in your portfolio</li>
              <li style={{ marginBottom: 8 }}>AI-drafted client email templates</li>
              <li style={{ marginBottom: 8 }}>Portfolio tracking and allocation visualization</li>
            </ul>
            The Service is a productivity tool for financial professionals and does not constitute investment advice, financial planning, or any regulated advisory service.
          </Section>

          <Section title="4. Subscription and Payment">
            <b style={{ color: 'var(--text)' }}>Free Trial:</b> New accounts receive a 14-day free trial with full access to the platform.
            <br /><br />
            <b style={{ color: 'var(--text)' }}>Billing:</b> After the trial period, continued use requires a paid subscription. Billing occurs monthly or annually as selected at checkout. All payments are processed by Stripe.
            <br /><br />
            <b style={{ color: 'var(--text)' }}>Cancellation:</b> You may cancel at any time through the billing portal. Access continues until the end of the current billing period. We do not provide prorated refunds for partial months.
            <br /><br />
            <b style={{ color: 'var(--text)' }}>Price Changes:</b> We reserve the right to change subscription pricing. We will provide at least 30 days' notice of any price increase to active subscribers.
          </Section>

          <Section title="5. Acceptable Use">
            You agree not to:
            <ul style={{ margin: '8px 0', paddingLeft: 20 }}>
              <li style={{ marginBottom: 8 }}>Use the Service for any unlawful purpose or in violation of any regulations, including securities laws</li>
              <li style={{ marginBottom: 8 }}>Redistribute, resell, or sublicense access to the Service</li>
              <li style={{ marginBottom: 8 }}>Attempt to reverse engineer, scrape, or extract data from the Service at scale</li>
              <li style={{ marginBottom: 8 }}>Use AI-generated briefing content as the sole basis for investment decisions or client recommendations without independent verification</li>
              <li style={{ marginBottom: 8 }}>Impersonate another person or create multiple accounts to circumvent subscription requirements</li>
              <li style={{ marginBottom: 8 }}>Attempt to circumvent security measures or access other users' data</li>
            </ul>
          </Section>

          <Section title="6. No Investment Advice">
            THE SERVICE DOES NOT PROVIDE INVESTMENT ADVICE. All content generated by the platform — including morning briefings, filing summaries, and client email drafts — is for informational and productivity purposes only. Nothing in the Service constitutes a recommendation to buy, sell, or hold any security.
            <br /><br />
            You are solely responsible for verifying the accuracy of AI-generated content before sharing it with clients or using it to inform any investment decision. See our full <button onClick={() => navigate('/disclaimer')} style={{ background: 'none', border: 'none', color: 'var(--accent)', cursor: 'pointer', padding: 0, fontFamily: 'inherit', fontSize: 14.5, textDecoration: 'underline' }}>Disclaimer</button>.
          </Section>

          <Section title="7. Accuracy of Information">
            We strive to provide accurate market data and filing summaries, but we do not guarantee the accuracy, completeness, or timeliness of any information provided. Market data is sourced from third-party providers and may be delayed. SEC filing summaries are AI-generated and may contain errors or omissions.
            <br /><br />
            Always verify critical information against primary sources (SEC EDGAR, exchange data, company filings) before relying on it.
          </Section>

          <Section title="8. Intellectual Property">
            The Service, including its interface, design, and underlying software, is owned by VeloQuant and protected by intellectual property laws. Your account and briefing history are yours. You retain ownership of the portfolio data you enter.
            <br /><br />
            AI-generated briefing content is provided for your personal professional use. You may share briefing summaries with your clients in the normal course of your advisory business.
          </Section>

          <Section title="9. Limitation of Liability">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, RIA INTELLIGENCE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOST PROFITS, INVESTMENT LOSSES, OR DATA LOSS, ARISING FROM YOUR USE OF THE SERVICE.
            <br /><br />
            OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.
          </Section>

          <Section title="10. Disclaimer of Warranties">
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.
          </Section>

          <Section title="11. Indemnification">
            You agree to indemnify and hold harmless VeloQuant from any claims, damages, or expenses (including legal fees) arising from your use of the Service, your violation of these Terms, or any content you share with third parties that was generated or modified using the Service.
          </Section>

          <Section title="12. Termination">
            We reserve the right to suspend or terminate your account at any time for violations of these Terms. You may delete your account at any time from the Settings page. Upon termination, your data will be deleted within 30 days.
          </Section>

          <Section title="13. Governing Law">
            These Terms are governed by the laws of the State of Texas, without regard to conflict of law principles. Any disputes shall be resolved exclusively in the state or federal courts located in Texas.
          </Section>

          <Section title="14. Changes to Terms">
            We may update these Terms from time to time. We will notify registered users of material changes by email at least 14 days before they take effect. Continued use of the Service after the effective date constitutes acceptance.
          </Section>

          <Section title="15. Contact">
            Questions about these Terms? Contact us at: <span style={{ color: 'var(--accent)' }}>vineet.sista@gmail.com</span>
          </Section>

        </div>
      </div>
    </div>
  )
}

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 32 }}>
      <h2 style={{ fontSize: 15, fontWeight: 700, color: 'var(--text)', marginBottom: 10, marginTop: 0 }}>{title}</h2>
      <div>{children}</div>
    </div>
  )
}
