"""add password_hash to advisors

Revision ID: 716427421af5
Revises: f2eceba356f2
Create Date: 2026-05-12 08:45:46.965428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716427421af5'
down_revision = 'f2eceba356f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
